---
- name: Provision MacOs Development Environment
  hosts: localhost
  connection: local

  tasks:
    - name: Provision Settings
      include_tasks: tasks/osx_settings.yaml

    - name: Install software
      include_tasks: tasks/brew-install.yaml

    - name: Install Emacs
      include_tasks: tasks/emacs/main.yml

    - name: Install Brave Browser
      include_tasks: tasks/brave-browser.yaml

    - name: Create ~/workspace
      ansible.builtin.file:
        path: ~/workspace
        state: directory
