---
- name: Provision MacOs Development Environment
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Install Ansible roles and collections
      ansible.builtin.command:
        cmd: ~/Library/Python/3.9/bin/ansible-galaxy install -r requirements.yml

  tasks:
    - name: Provision Settings
      include_tasks: tasks/osx_settings.yaml

    - name: Install software
      include_tasks: tasks/brew-install.yaml

    - name: Create ~/workspace
      ansible.builtin.file:
        path: ~/workspace
        state: directory

  roles:
    - role: professormanhattan.bravebrowser
    # - name: Install Brave Browser
    #   shiftsystems.general:
    #     role: brave
