---
- name: Is Brave Browser installed
  stat:
    path: /Applications/Brave Browser.app/
  register: brave_check

- name: Download Brave Browser
  ansible.builtin.get_url:
    url: https://referrals.brave.com/latest/BRV002/Brave-Browser.dmg
    dest: /tmp/brave_browser.dmg
  when:
    - not brave_check.stat.exists

- name: Mount Brave Browser dmg
  command: hdiutil attach /tmp/brave_browser.dmg -nobrowse -mountpoint /tmp/brave_browser
  when:
    - not brave_check.stat.exists

- name: Install Brave Browser
  shell: cp -R /tmp/brave_browser/Brave\ Browser.app /Applications/Brave\ Browser.app
  when:
    - not brave_check.stat.exists

- name: Unmount Brave Browser dmg
  command: hdiutil detach /tmp/brave_browser
  when:
    - not brave_check.stat.exists

- name: Remove Brave Browser dmg
  command: rm /tmp/brave_browser.dmg
  when:
    - not brave_check.stat.exists
