---
- stat:
    path: ~/.sdkman
  register: sdkman_check

- name: Install SDKMan
  shell: curl -s "https://get.sdkman.io" | bash
  when: not sdkman_check.stat.exists

- name: Setup SDKMan
  shell: source ~/.sdkman/bin/sdkman-init.sh
  when: not sdkman_check.stat.exists

- name: SDKMan Java 21.0.4-tem
  shell: sdk install java 21.0.4-tem
  when: not sdkman_check.stat.exists
